;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	electric-newline-and-maybe-indent
	electric-pair-delete-pair
	elpy-nav-indent-shift-right
	ensime-company-complete-or-indent
	exit-recursive-edit
	graphviz-dot-preview
	helm-M-x
	indent-for-tab-command
	js2r-kill
	kill-region
	mouse-save-then-kill
	org-beginning-of-line
	org-ctrl-c-ctrl-c
	org-cycle
	org-end-of-line
	org-force-self-insert
	org-meta-return
	org-metaleft
	org-metaright
	org-self-insert-command
	org-table-copy-down
	rjsx-electric-gt
	rjsx-electric-lt
	sh-assignment
	winner-redo
	yaml-electric-backspace
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	ein:worksheet-execute-cell-and-goto-next
	elpy-nav-indent-shift-left
	end-of-buffer
	ensime-mouse-motion
	help-for-help
	ignore
	mac-mouse-buffer-menu
	mac-mwheel-scroll
	mac-previous-buffer
	mark-whole-buffer
	mouse-set-region
	multiple-cursors-mode
	phi-search
	projectile-find-file
	python-shell-send-buffer
	set-selective-display
	tmm-menubar
	))
